### ISSUE TITLE
Update theme sorcebans

### ISSUE THREAD

**Issue by ThanhByKyTa** [brhndursun/SourceBans-StarTheme#7]
Can you update version SourceBans++ 1.7.0 | Git: 931 ?

**Comment by brhndursun** [comment]
I was waiting for a new template engine but most of people keep asking for 1.7.0 so I'm working on a new project (DiamondTheme)

Still working on it. It has dark and light color option and a customize page.

**Comment by paulocrash** [comment]
@brhndursun  I even understand your point of view in expecting the new template, but I believe that this new version will take still, or would you have some release information? I myself have never encountered release information or planned date.

In any case I will be waiting for this new DiamondTheme project.

And I would like to know if you still want to fix BUGS of this theme in case if they are reported, I really like this theme. :)

**Comment by brhndursun** [comment]
Well, I've asked to developers for new template engine update and release date for 1.7
He said that can take quite a while

Maybe I should make star theme dark and light color
I have fixed most of the bugs btw...

Also I am waiting for an answer from star theme creators to make a dark theme. 

I will release a new fix asap

Shortly, I will fix bugs and make dark color option for star theme if they let me do it.

Cheerz

**Comment by ThanhByKyTa** [comment]
Theme Star not working version SourceBans++ 1.7.0 | Git: 931
![image](https://user-images.githubusercontent.com/33537916/58712679-3f0ed280-83eb-11e9-9193-2fad57ce8746.png)

**Comment by Drmohammad11** [comment]
error:

Fatal error: Uncaught Mustache_Exception_UnknownTemplateException: Unknown template: core/header in C:\xampp\htdocs\cp-toosgame\includes\Mustache\Loader\FilesystemLoader.php:102 Stack trace: #0 C:\xampp\htdocs\cp-toosgame\includes\Mustache\Loader\FilesystemLoader.php(82): Mustache_Loader_FilesystemLoader->loadFile('core/header') #1 C:\xampp\htdocs\cp-toosgame\includes\Mustache\Engine.php(657): Mustache_Loader_FilesystemLoader->load('core/header') #2 C:\xampp\htdocs\cp-toosgame\includes\Template.php(14): Mustache_Engine->loadTemplate('core/header') #3 C:\xampp\htdocs\cp-toosgame\pages\core\header.php(12): Template::render('core/header', Array) #4 C:\xampp\htdocs\cp-toosgame\includes\page-builder.php(130): require_once('C:\\xampp\\htdocs...') #5 C:\xampp\htdocs\cp-toosgame\index.php(37): build('SourceBans++ Se...', '/admin.settings...') #6 {main} thrown in C:\xampp\htdocs\cp-toosgame\includes\Mustache\Loader\FilesystemLoader.php on line 102

**Comment by distratul** [comment]
Can you fix theme for 1.6.3?

**Comment by crashzk** [comment]
@brhndursun abandoned project? Won't we have more updates?

**Comment by azalty** [comment]
any news about the theme?
